# SITE CONFIGURATION
title: "Lizzy's Blog"
author: Liz Ainslie
description: Welcome, I guess...
url: "https://lizainslie.github.io/"

# SEO PLUGIN
social:
  name: Liz Ainslie
  links:
    - https://twitter.com/LizzyReborn
    - https://github.com/LizAinslie
    - https://synapsetech.dev

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}

tagline: "Welcome, I guess..."

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

twitter_username: LizzyReborn
github_username:  LizAinslie

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:year/:month/:day/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
